spring.application.name=gateway
server.port=8084

#Eureka Cloud configurations
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
eureka.instance.hostname=localhost
eureka.instance.instance-id=${eureka.instance.hostname}:${spring.application.name}:${server.port}
eureka.instance.status-page-url=http://${eureka.instance.hostname}:${server.port}/

#zipkin
management.tracing.sampling.probability=1.0

#Gateway
spring.cloud.gateway.server.webmvc.routes[0].id=job-service
spring.cloud.gateway.server.webmvc.routes[0].uri=lb://JOBMS
spring.cloud.gateway.server.webmvc.routes[0].predicates[0]=Path=/jobs/**

spring.cloud.gateway.server.webmvc.routes[1].id=company-service
spring.cloud.gateway.server.webmvc.routes[1].uri=lb://COMPANYMS
spring.cloud.gateway.server.webmvc.routes[1].predicates[0]=Path=/company/**

spring.cloud.gateway.server.webmvc.routes[2].id=review-service
spring.cloud.gateway.server.webmvc.routes[2].uri=lb://REVIEWMS
spring.cloud.gateway.server.webmvc.routes[2].predicates[0]=Path=/review/**

logging.level.root=info
logging.level.org.springframework.cloud.gateway.route.RouteDefinitionLocator=INFO
logging.level.org.springframework.cloud.gateway=TRACE